name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-20.04
    steps:
      - name: List Files
        run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $GITHUB_WORKSPACE
            echo "${{ github.token }}"
            # git clone git@github:$GITHUB_REPOSITORY
            # git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@master
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"